# Generated by Django 4.1.7 on 2023-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
    ]
