# Generated by Django 4.1.7 on 2023-03-10 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtimemodel',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
